
version: 1.0.{branch}-{build}

image: Visual Studio 2015

clone_depth: 5

skip_tags: true

configuration:
  - Release
  - Debug

platform:
  - x64
#  - x86

environment:
  matrix:
   - PROFILE: MSVC2015
     CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
     CMAKE_OPTIONS: " "

install:
  - bash buildscripts\1-install-deps-appveyor.sh
  - refreshenv
  - set PATH=%APPVEYOR_BUILD_FOLDER%\temp;%PATH%

build_script:
  - bash buildscripts\2-build-appveyor.sh

on_success:
  - bash buildscripts\3-release-appveyor.sh

